FROM debian:testing
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    git \
    python3-pip \
    gnupg2 \
    dirmngr \
    apt-transport-https \
    curl \
    init \
    openssh-server openssh-client \
    systemd \
    unzip \
    rsync \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ansible \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
