FROM opensuse/leap:42.3
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

ENV container docker

RUN zypper -n install systemd; zypper clean ; \
(cd /usr/lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /usr/lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /usr/lib/systemd/system/local-fs.target.wants/*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /usr/lib/systemd/system/basic.target.wants/*;\
rm -f /usr/lib/systemd/system/anaconda.target.wants/*;

# Install python pip
RUN zypper -n install git \
                      gcc \
                      make \
                      python-pip \
                      python-devel \
                      libffi-devel \
                      openssl-devel \
                      sudo \
                      openssh && \
                      zypper clean

# Install Ansible
RUN pip install --no-cache-dir --upgrade setuptools && \
    pip install --no-cache-dir ansible==2.7

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible && \
    echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/lib/systemd/systemd", "--system"]
