FROM centos:6
MAINTAINER diodonfrost <diodonfrost@protonmail.com>

RUN yum -y install epel-release
RUN yum -y install git ansible sudo openssh-server openssh-clients

RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]

CMD ["/sbin/init"]
