FROM clearlinux:latest
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

# Install ansible
RUN swupd bundle-add ansible unzip

RUN mkdir -p /etc/ansible && \
    echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]

ENTRYPOINT ["/usr/sbin/init"]
