FROM ubuntu:14.04
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

RUN apt-get update && apt-get install -y \
    git \
    python-pip \
    python-dev \
    apt-transport-https \
    libssl-dev \
    libffi-dev \
    curl \
    openssh-server openssh-client \
    && rm -rf /var/lib/apt/lists/*

 # Install Ansible
 RUN pip install --upgrade setuptools && \
     pip install markupsafe ansible==2.6

 # Install Ansible inventory file.
 RUN mkdir -p /etc/ansible && \
     echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
