FROM amazonlinux:2023
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

RUN dnf -y install \
    git \
    python3-pip \
    openssh-server \
    openssh-clients \
    unzip \
    tar \
    rsync \
    sudo \
    which \
    fuse-libs \
    && dnf clean all

RUN python3 -m pip install ansible

# Install Ansible inventory file.
RUN mkdir /etc/ansible && \
    echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

CMD ["/usr/sbin/init"]
