FROM ubuntu:16.04
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    apt-transport-https \
    libssl-dev \
    libffi-dev \
    curl \
    openssh-server openssh-client \
    && rm -rf /var/lib/apt/lists/*

 # Install Ansible
 RUN pip3 install --no-cache-dir --upgrade setuptools && \
     pip3 install --no-cache-dir ansible==2.8

 # Install Ansible inventory file.
 RUN mkdir -p /etc/ansible && \
     echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
