FROM opensuse:13.2
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

ENV container docker

RUN zypper -n install systemd; zypper clean ; \
(cd /usr/lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /usr/lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /usr/lib/systemd/system/local-fs.target.wants/*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /usr/lib/systemd/system/basic.target.wants/*;\
rm -f /usr/lib/systemd/system/anaconda.target.wants/*;

# Install packages requirements
RUN zypper -n install git \
                      python-pip \
                      python-devel \
                      gcc \
                      make \
                      libopenssl-devel \
                      libffi-devel \
                      sudo \
                      openssh && \
                      zypper clean

# Install Ansible
RUN pip install -U setuptools && \
    pip install markupsafe && \
    pip install ansible

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/lib/systemd/systemd", "--system"]
