FROM alpine:latest
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

# Install Ansible
RUN apk add --no-cache git ansible sudo openssh unzip rsync

VOLUME ["/sys/fs/cgroup"]

ENTRYPOINT ["/sbin/init"]
