name: Build

on:
  push:
    paths:
      - 'ubuntu-ansible/**'
  pull_request:
    paths:
      - 'ubuntu-ansible/**'
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: ubuntu
            version: "14.04"
            platform: "linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8"
          - image: ubuntu
            version: "16.04"
            platform: "linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8"
          - image: ubuntu
            version: "18.04"
            platform: "linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8"
          - image: ubuntu
            version: "20.04"
            platform: "linux/amd64,linux/arm/v7,linux/arm64/v8"
          - image: ubuntu
            version: "22.04"
            platform: "linux/amd64,linux/arm/v7,linux/arm64/v8"
          - image: ubuntu
            version: "24.04"
            platform: "linux/amd64,linux/arm/v7,linux/arm64/v8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 5.21.29

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          no-cache: true
          load: true
          file: ${{ matrix.distribution.image }}-ansible/Dockerfile.${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
          tags: diodonfrost/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }}
          context: ${{ matrix.distribution.image }}-ansible

      - name: Test Docker images
        run: |
          container_id=$(mktemp)
          sudo docker run \
            --detach \
            --privileged \
            --cgroupns=host \
            -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
            -v /var/lib/containerd \
            diodonfrost/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} > "${container_id}"

          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})

      - name: Build images on multiple platforms
        uses: docker/build-push-action@v4
        with:
          no-cache: true
          platforms: ${{ matrix.distribution.platform }}
          file: ${{ matrix.distribution.image }}-ansible/Dockerfile.${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
          tags: diodonfrost/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }}
          context: ${{ matrix.distribution.image }}-ansible